import { Product, Service } from '@/types/products';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Cotización de Herramientas Industriales',
    category: 'Herramientas',
    description: 'Servicio de cotización personalizada para herramientas neumáticas, eléctricas y manuales. Contamos con equipos de alta calidad de marcas reconocidas para todas sus necesidades de mantenimiento y operación industrial.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Tipo de Herramientas', value: 'Neumáticas, Eléctricas, Manuales' },
      { label: 'Disponibilidad', value: 'Bajo demanda' },
      { label: 'Marcas', value: 'SKF, Bosch, Stanley, y más' },
      { label: 'Servicio', value: 'Cotización personalizada sin costo' },
    ],
  },
  {
    id: 'prod-001-en',
    name: 'Industrial Tools Quotation Request',
    category: 'Herramientas',
    description: 'Personalized quotation service for pneumatic, electric, and manual tools. We offer high-quality equipment from recognized brands for all your industrial maintenance and operation needs.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Tool Types', value: 'Pneumatic, Electric, Manual' },
      { label: 'Availability', value: 'On demand' },
      { label: 'Brands', value: 'SKF, Bosch, Stanley, and more' },
      { label: 'Service', value: 'Free personalized quotation' },
    ],
  },
  {
    id: 'prod-002',
    name: 'Kit Electrodos Soldadura E6010',
    category: 'Soldadura Industrial',
    description: 'Kit profesional de electrodos E6010 para soldadura especializada en acero al carbono, penetración profunda y acabado profesional.',
    price: 180000,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Tipo', value: 'E6010' },
      { label: 'Diámetro', value: '3.2mm' },
      { label: 'Cantidad', value: '5kg' },
      { label: 'Aplicación', value: 'Acero al Carbono' },
    ],
  },
  {
    id: 'prod-009',
    name: 'Solicitud de Cotización de Soldaduras Especiales',
    category: 'Soldadura Industrial',
    description: 'Cotización de trabajos de soldadura especializada: TIG/MIG láser, arco sumergido y soldadura en campo para acero al carbono e inoxidable.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092334420-22b676f19f2a?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Procesos', value: 'TIG, MIG, láser, arco sumergido y SMAW en campo' },
      { label: 'Materiales', value: 'Acero al carbono, inoxidable 304/316 y aluminio' },
      { label: 'Aplicaciones', value: 'Tubería de proceso, estructuras y recipientes' },
      { label: 'Servicio', value: 'Cotización según espesor, posición y certificaciones requeridas' },
    ],
  },
  {
    id: 'prod-009-en',
    name: 'Specialized Welding Quotation Request',
    category: 'Soldadura Industrial',
    description: 'Quotation for specialized welding work: TIG/MIG laser, submerged arc and field welding for carbon steel and stainless steel.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092334420-22b676f19f2a?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Processes', value: 'TIG, MIG, laser, submerged arc and SMAW field' },
      { label: 'Materials', value: 'Carbon steel, stainless 304/316 and aluminum' },
      { label: 'Applications', value: 'Process piping, structures and vessels' },
      { label: 'Service', value: 'Quote based on thickness, position and certifications required' },
    ],
  },
  {
    id: 'prod-003',
    name: 'Sensor de Proximidad Industrial',
    category: 'Automatización',
    description: 'Sensor de proximidad inductivo de alto rendimiento para sistemas de automatización en líneas de producción.',
    price: 320000,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Tipo', value: 'Inductivo' },
      { label: 'Rango', value: '0-8mm' },
      { label: 'Voltaje', value: '10-30VDC' },
      { label: 'Protección', value: 'IP67' },
    ],
  },
  {
    id: 'prod-010',
    name: 'Solicitud de Cotización de Automatización Especializada',
    category: 'Automatización',
    description: 'Cotización de proyectos de automatización industrial e IA: actuadores, controladores, PLC/SCADA y software a la medida para optimizar procesos.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Servicios', value: 'Automatización con IA, PLC, SCADA y control distribuido' },
      { label: 'Equipos', value: 'Actuadores, controladores, variadores y sensores de proceso' },
      { label: 'Software', value: 'Integración, HMI y desarrollos a la medida' },
      { label: 'Servicio', value: 'Cotización según I/O, alcance, certificaciones y puesta en marcha' },
    ],
  },
  {
    id: 'prod-010-en',
    name: 'Specialized Automation Quotation Request',
    category: 'Automatización',
    description: 'Quotation for industrial automation and AI projects: actuators, controllers, PLC/SCADA and custom software to optimize processes.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Services', value: 'AI automation, PLC, SCADA and distributed control' },
      { label: 'Equipment', value: 'Actuators, controllers, drives and process sensors' },
      { label: 'Software', value: 'Integration, HMI and custom developments' },
      { label: 'Service', value: 'Quote based on I/O, scope, certifications and commissioning' },
    ],
  },
  {
    id: 'prod-004',
    name: 'Materiales de Construcción Mixtos',
    category: 'Materiales',
    description: 'Cotización de materiales de construcción: madera estructural, concreto premezclado y láminas metálicas en acero, aluminio y galvanizado.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Madera', value: 'Pino inmunizado y madera estructural en varias secciones' },
      { label: 'Concreto', value: 'Premezclado 3000-5000 PSI y morteros secos' },
      { label: 'Láminas Metálicas', value: 'Acero al carbono, aluminio y galvanizado en diferentes calibres' },
      { label: 'Servicio', value: 'Cotización según volumen, calibre y resistencia requerida' },
    ],
  },
  {
    id: 'prod-004-en',
    name: 'Mixed Construction Materials Quotation Request',
    category: 'Materiales',
    description: 'Quotation for construction materials: structural wood, ready-mix concrete and metal sheets in steel, aluminum and galvanized.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Wood', value: 'Treated pine and structural wood in various sections' },
      { label: 'Concrete', value: 'Ready-mix 3000-5000 PSI and dry mortars' },
      { label: 'Metal Sheets', value: 'Carbon steel, aluminum and galvanized in different gauges' },
      { label: 'Service', value: 'Quote based on volume, gauge and strength required' },
    ],
  },
  {
    id: 'prod-008',
    name: 'Tubo Galvanizado Schedule 40',
    category: 'Suministros',
    material: 'Galvanizado',
    description: 'Tubería galvanizada schedule 40 de alta calidad para aplicaciones industriales y construcción de estructuras.',
    price: 95000,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Material', value: 'Acero Galvanizado' },
      { label: 'Diámetro', value: '1 pulgada' },
      { label: 'Longitud', value: '6 metros' },
      { label: 'Schedule', value: '40' },
    ],
  },
  {
    id: 'prod-005',
    name: 'Herramientas Neumáticas',
    category: 'Herramientas',
    description: 'Llave de impacto neumática de alta potencia para mantenimiento industrial, ideal para ensamblaje y desarmado de maquinaria.',
    price: 850000,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Torque', value: '1200 Nm' },
      { label: 'Presión', value: '90 PSI' },
      { label: 'Cuadro', value: '1/2 pulgada' },
      { label: 'Peso', value: '2.3 kg' },
    ],
  },
  {
    id: 'prod-006',
    name: 'Rodamiento SKF 6205-2RS',
    category: 'Mantenimiento',
    description: 'Rodamiento de bolas sellado SKF de alta precisión para mantenimiento de motores y equipos rotativos industriales.',
    price: 65000,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Marca', value: 'SKF' },
      { label: 'Modelo', value: '6205-2RS' },
      { label: 'Diámetro Interior', value: '25mm' },
      { label: 'Diámetro Exterior', value: '52mm' },
    ],
  },
  {
    id: 'prod-011',
    name: 'Solicitud de Mantenimiento y Servicio en Campo',
    category: 'Mantenimiento',
    description: 'Cotización de mantenimiento preventivo y correctivo, reparación de válvulas, nuevas instalaciones y soporte en campo para líneas de proceso.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092334420-22b676f19f2a?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Alcance', value: 'Mantenimiento preventivo, correctivo y nuevas instalaciones' },
      { label: 'Equipos', value: 'Válvulas, bombas, actuadores y líneas de proceso' },
      { label: 'Modalidad', value: 'Trabajo en campo y en taller con reporte técnico' },
      { label: 'Servicio', value: 'Cotización según criticidad, SLA, repuestos y desplazamiento' },
    ],
  },
  {
    id: 'prod-011-en',
    name: 'Maintenance and Field Service Quotation Request',
    category: 'Mantenimiento',
    description: 'Quotation for preventive and corrective maintenance, valve repair, new installations and field support for process lines.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092334420-22b676f19f2a?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Scope', value: 'Preventive, corrective maintenance and new installations' },
      { label: 'Equipment', value: 'Valves, pumps, actuators and process lines' },
      { label: 'Modality', value: 'Field and workshop work with technical report' },
      { label: 'Service', value: 'Quote based on criticality, SLA, spare parts and travel' },
    ],
  },
  {
    id: 'prod-007',
    name: 'Solicitud de Cotización de Suministros y Tuberías',
    category: 'Suministros',
    description: 'Cotización integral de suministros industriales: tuberías, válvulas y acoples en acero inoxidable, galvanizado y acero al carbono para líneas de proceso, agua y vapor.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Tuberías', value: 'Acero inoxidable (304/316), galvanizado, acero al carbono' },
      { label: 'Válvulas', value: 'Bola, compuerta y check en bronce, inoxidable y hierro dúctil' },
      { label: 'Acoples', value: 'Galvanizados, acero inoxidable y ranurados para instalación rápida' },
      { label: 'Servicio', value: 'Cotización personalizada según diámetro, schedule y presión' },
    ],
  },
  {
    id: 'prod-007-en',
    name: 'Supplies and Piping Quotation Request',
    category: 'Suministros',
    description: 'Comprehensive quotation for industrial supplies: pipes, valves and fittings in stainless steel, galvanized and carbon steel for process, water and steam lines.',
    price: 0,
    currency: 'COP',
    image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&h=600&fit=crop',
    inStock: true,
    specifications: [
      { label: 'Piping', value: 'Stainless steel (304/316), galvanized, carbon steel' },
      { label: 'Valves', value: 'Ball, gate and check in bronze, stainless and ductile iron' },
      { label: 'Fittings', value: 'Galvanized, stainless steel and grooved for quick installation' },
      { label: 'Service', value: 'Customized quote based on diameter, schedule and pressure' },
    ],
  },
];

export const SERVICES: Service[] = [
  {
    id: 'service-001',
    title: 'Suministros y Herramientas',
    description: 'Amplio catálogo de herramientas y suministros para mantenimiento de líneas de producción industrial.',
    icon: 'Wrench',
    features: [
      'Más de 500 productos en stock',
      'Marcas reconocidas internacionalmente',
      'Entrega rápida en Colombia',
      'Asesoría técnica especializada',
    ],
  },
  {
    id: 'service-002',
    title: 'Materiales Especializados',
    description: 'Distribución de materiales industriales de alta calidad en diferentes especificaciones.',
    icon: 'Boxes',
    features: [
      'Acero Inoxidable (304, 316, 430)',
      'Acero al Carbono',
      'Hierro y derivados',
      'Materiales galvanizados',
    ],
  },
  {
    id: 'service-003',
    title: 'Instalación y Consultoría',
    description: 'Servicios profesionales de instalación y consultoría para optimizar sus procesos industriales.',
    icon: 'Handshake',
    features: [
      'Instalación de equipos',
      'Mantenimiento preventivo',
      'Diagnóstico de procesos',
      'Optimización de líneas',
      'Soporte técnico continuo',
    ],
  },
  {
    id: 'service-004',
    title: 'Automatización de Procesos',
    description: 'Soluciones integrales de automatización para aumentar la eficiencia de su producción.',
    icon: 'Cpu',
    features: [
      'Sensores y controladores',
      'Sistemas PLC',
      'Integración de sistemas',
      'Programación personalizada',
    ],
  },
  {
    id: 'service-005',
    title: 'Soldadura Especializada',
    description: 'Servicios de soldadura profesional para aplicaciones industriales exigentes.',
    icon: 'Flame',
    features: [
      'Soldadura TIG y MIG',
      'Soldadura en acero inoxidable',
      'Reparación de estructuras',
      'Certificación de soldaduras',
    ],
  },
];

export const MATERIALS = [
  'Acero Inoxidable',
  'Acero al Carbono',
  'Hierro',
  'Galvanizado',
];

export const CATEGORIES = [
  'Herramientas',
  'Suministros',
  'Materiales',
  'Soldadura Industrial',
  'Automatización',
  'Mantenimiento',
];
